### ISSUE TITLE
pam_systemd.so shouldn't be invoked from system-auth

### ISSUE THREAD

**Issue by msekletar** [authselect/authselect#263]
Currently, `pam_systemd.so` is invoked by `system-auth`. Since `system-auth` is in turn included by many services we start `systemd --user` sessions also in cases where it is not desirable or useful (e.g. cron invocations, ftp sessions). `systemd --user` instances should run only for actual user login sessions (local and remote) but shouldn't be started for services that don't provide full shell access after login.

See also, https://bugzilla.redhat.com/show_bug.cgi?id=1942956

**Comment by pbrezina** [comment]
Isn't this something that should be handled in pam_systemd? It can check what pam service called this module and act accordingly. This will also make it future proof - if pam_systemd would need to do some action for some service it will not require pam stack update.

**Comment by msekletar** [comment]
My motivation behind the issue was to get your opinion. Since you think it should be handled by pam_systemd then let's close the issue and handle this in pam_systemd.

**Comment by pbrezina** [comment]
Cool :-) I would prefer to handle it in pam_systemd directly so you guys have more control without touching pam. However if there are some concerns we can also do it in the pam stack and whitelist required services using pam_succeed_if.

**Comment by rpigott** [comment]
I'm not sure a whitelist of service names makes sense in pam_systemd. Surely it would be better to keep this configurable within the pam configs, right?

Either way, the feature was never implemented in pam_systemd, but this undesirable behavior remains. Can we reconsider removing pam_systemd from `system-auth`?

**Comment by pbrezina** [comment]
> I'm not sure a whitelist of service names makes sense in pam_systemd. Surely it would be better to keep this configurable within the pam configs, right?

Why? How can I decide what services pam_systemd wants to handle? I will need to ask them to provide whitelist and then they will have to come to me if they ever want to change it. For this reason, it would be much better if this is controlled by the party that has the knowledge.

> Either way, the feature was never implemented in pam_systemd, but this undesirable behavior remains. Can we reconsider removing pam_systemd from `system-auth`?

@msekletar Loud ping ;-) Do you have a ticket?

**Comment by rpigott** [comment]
> How can I decide what services pam_systemd wants to handle?

How can pam_systemd decide what services the administrator wants it to handle?

You leave it to the administrator rather than hardcoding a whiltelist in some binary. That's why pam has configuration files in the first place, no?

FWIW on Arch in the default configs there exists "system-login" which includes system-auth and also pam_loginuid, pam_systemd etc. modules which are useful for user logins. Then configs like sudo include system-auth while others like sshd include system-login, which seems a much more sensible default.

**Comment by pbrezina** [comment]
> > How can I decide what services pam_systemd wants to handle?
> 
> How can pam_systemd decide what services the administrator wants it to handle?
> 
> You leave it to the administrator rather than hardcoding a whiltelist in some binary. That's why pam has configuration files in the first place, no?

systemd knows which services should create new session and which not, I doubt that anyone wants to change that. But no one is talking about hardcoding it, they can make it configurable.

Having it in authselect profile will in fact make it hardcoded. You'd need to create custom profile in order to change that. The systemd implementation can make the list configurable (authselect can not) and they can use whatever default they think is the best.

**Comment by msekletar** [comment]
> @msekletar Loud ping ;-) Do you have a ticket?

I don't need a ticket for everything ;-)

Anyways, I was working on this in systemd upstream here https://github.com/systemd/systemd/pull/23569 but later my changes were reverted and reworked by Lennart here https://github.com/systemd/systemd/pull/30884. I didn't experiment with this background-light session so I don't know if it fixes the original issue.

Maybe @rpigott can double check on that and let systemd folks know if current state is good enough.

**Comment by keszybz** [comment]
Logistically, I think it's easier if this is done on the systemd side. The internals of systemd session handling seem to change with some regularity, and thus it makes sense for the configuration to change with systemd versions too. If we put this config here in the pam stack, it'd be quite hard to change it. So I think we should figure this out on the systemd side first, and _maybe_, if it turns out that some parts should be configurable by users, consider adjusting the config here.
